id: P94986848
initial_creation_type: input
source_metadata:
  title: Sang Offering
  language: pt
  description: 'Texts on the subject of Sang (bsang/bsangs) or Purificatory Incense
    Smoke Offering:'
  volume:
    c0dc184a5f414e19993296e288773acf:
      title: A Guide to the Practice of Sang
      parent: Commentaries
    83e8faf4dce34fe58069b44da2f93a55:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    21240147554740dc9a933e6cecd69ac7:
      title: Yarlha Shampo Sang Offering
      parent: Dharma Protectors
    2eab4025b19c47aebfd4a9e0d3ee2246:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    3d95a321e53c447da0b9803d47480ad4:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    b202d77d54fe439db65a877d9f95f694:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Rituals
    e80d598e7c3d4bbf8ee03aaf0e991b54:
      title: Sang Offering to Yellow Jambhala
      parent: Rituals
    4dd78f0c8676499cb666a5d34198070d:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Rituals
    9c06ba7489234268b2d6ec78e769fafa:
      title: 'Lasel Chenmo: A Sang Offering to the Nāgas'
      parent: Rituals
    91a00d24609e4e2c8b270c813b0f71a6:
      title: Brief Sang Offering
      parent: Rituals
    81d6470287c643e18ae6d8305b662d2d:
      title: Brief Sang Offering to Purify Contamination
      parent: Rituals
    ec518c2341e947cda6283ba4c51e9a2c:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Rituals
    9b27ecfb23134411b6a2cb033237bc04:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Riwo Sangchö
    10759f710ff14fd8925cfd1fabe6d1fb:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Riwo Sangchö
    6a732b64e3244dcaa580462e0c1359f1:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Riwo Sangchö
    0b1bc5416dc045d1a0e75a4cbd239168:
      title: A Concise Sang Offering to Tārā
      parent: Tārā
created_at: '2022-03-01T05:40:37.294008'
last_modified_at: '2022-03-01T05:40:37.294010'
